### ISSUE TITLE
如果登入後如果沒有 event， console 會跑出如下錯誤

### ISSUE THREAD

**Issue by tonytonyjan** [tonytonyjan/good_lock#1]
@fukuball 

我在想有可能我哪裡設定錯誤，不知道你是否也有一樣的狀況？

```
TypeError: Cannot call method 'split' of undefined
    at s.e.pushEvents (http://localhost:3000/assets/application-325a07a4c29d72e1811d609d11576d93.js:10:22562)
    at http://localhost:3000/assets/application-325a07a4c29d72e1811d609d11576d93.js:10:19853
    at http://localhost:3000/assets/application-325a07a4c29d72e1811d609d11576d93.js:5:5168
    at l (http://localhost:3000/assets/application-325a07a4c29d72e1811d609d11576d93.js:5:17622)
    at l (http://localhost:3000/assets/application-325a07a4c29d72e1811d609d11576d93.js:5:17622)
    at http://localhost:3000/assets/application-325a07a4c29d72e1811d609d11576d93.js:5:18299
    at s.$eval (http://localhost:3000/assets/application-325a07a4c29d72e1811d609d11576d93.js:5:22274)
    at s.$digest (http://localhost:3000/assets/application-325a07a4c29d72e1811d609d11576d93.js:5:21146)
    at s.$apply (http://localhost:3000/assets/application-325a07a4c29d72e1811d609d11576d93.js:5:22604)
    at o (http://localhost:3000/assets/application-325a07a4c29d72e1811d609d11576d93.js:5:5403) 
```

**Comment by fukuball** [comment]
目前已不再更新了，我來將 issue close
